name: Build and Deploy

on:
  push:
    branches:
      - main
      - 'project/**'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Get branch name
        id: branch-name
        run: |
          if [[ $GITHUB_REF == refs/heads/project/* ]]; then
            echo "BRANCH_PATH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          else
            echo "BRANCH_PATH=main" >> $GITHUB_ENV
          fi

      - name: Build the JupyterLite site
        run: |
          # Create branch-specific directory
          mkdir -p dist/${{ env.BRANCH_PATH }}
          
          # Build JupyterLite for this branch
          jupyter lite build --contents notebooks --output-dir dist/${{ env.BRANCH_PATH }}

      # If this is the main branch, also build the root
      - name: Build root site
        if: github.ref == 'refs/heads/main'
        run: |
          jupyter lite build --contents notebooks --output-dir dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/project/')
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4